apiVersion: v1
kind: ServiceAccount
metadata:
  name: nimbul-controller
  namespace: nimbul-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nimbul-controller
rules:
  - apiGroups: [""]
    resources: ["namespaces","services","configmaps","secrets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nimbul-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nimbul-controller
subjects:
  - kind: ServiceAccount
    name: nimbul-controller
    namespace: nimbul-system
